// Code generated by protoc-gen-go. DO NOT EDIT.
// source: points_mall.proto

package points_mall

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c75ba8dc07a9bf, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c75ba8dc07a9bf, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HiRequst struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiRequst) Reset()         { *m = HiRequst{} }
func (m *HiRequst) String() string { return proto.CompactTextString(m) }
func (*HiRequst) ProtoMessage()    {}
func (*HiRequst) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c75ba8dc07a9bf, []int{2}
}

func (m *HiRequst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiRequst.Unmarshal(m, b)
}
func (m *HiRequst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiRequst.Marshal(b, m, deterministic)
}
func (m *HiRequst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiRequst.Merge(m, src)
}
func (m *HiRequst) XXX_Size() int {
	return xxx_messageInfo_HiRequst.Size(m)
}
func (m *HiRequst) XXX_DiscardUnknown() {
	xxx_messageInfo_HiRequst.DiscardUnknown(m)
}

var xxx_messageInfo_HiRequst proto.InternalMessageInfo

func (m *HiRequst) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PayCoinReq struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Sign                 string   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	OrderNo              string   `protobuf:"bytes,4,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Account              string   `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayCoinReq) Reset()         { *m = PayCoinReq{} }
func (m *PayCoinReq) String() string { return proto.CompactTextString(m) }
func (*PayCoinReq) ProtoMessage()    {}
func (*PayCoinReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c75ba8dc07a9bf, []int{3}
}

func (m *PayCoinReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayCoinReq.Unmarshal(m, b)
}
func (m *PayCoinReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayCoinReq.Marshal(b, m, deterministic)
}
func (m *PayCoinReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayCoinReq.Merge(m, src)
}
func (m *PayCoinReq) XXX_Size() int {
	return xxx_messageInfo_PayCoinReq.Size(m)
}
func (m *PayCoinReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayCoinReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayCoinReq proto.InternalMessageInfo

func (m *PayCoinReq) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *PayCoinReq) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *PayCoinReq) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *PayCoinReq) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *PayCoinReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PayCoinReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "points_mall.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "points_mall.HelloReply")
	proto.RegisterType((*HiRequst)(nil), "points_mall.HiRequst")
	proto.RegisterType((*PayCoinReq)(nil), "points_mall.PayCoinReq")
}

func init() { proto.RegisterFile("points_mall.proto", fileDescriptor_f7c75ba8dc07a9bf) }

var fileDescriptor_f7c75ba8dc07a9bf = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xbf, 0x4a, 0x04, 0x31,
	0x10, 0xc6, 0x5d, 0xbd, 0x7f, 0x8e, 0x5a, 0x18, 0x04, 0xa3, 0x85, 0x48, 0x0a, 0xb1, 0xba, 0x42,
	0x5f, 0x40, 0x11, 0xf1, 0x6c, 0x44, 0xd6, 0x07, 0x90, 0x78, 0x37, 0x2c, 0x81, 0x6c, 0x32, 0x97,
	0xe4, 0x8a, 0xbc, 0xc6, 0x3e, 0xb1, 0x24, 0x9b, 0xc5, 0x2d, 0xb4, 0xb1, 0x9b, 0x6f, 0xbe, 0x1f,
	0xdf, 0x4c, 0x26, 0x70, 0x4a, 0x56, 0x99, 0xe0, 0x3f, 0x5b, 0xa9, 0xf5, 0x92, 0x9c, 0x0d, 0x96,
	0x1d, 0x8d, 0x5a, 0x42, 0xc0, 0xf1, 0x0a, 0xb5, 0xb6, 0x35, 0x6e, 0x77, 0xe8, 0x03, 0x63, 0x30,
	0x31, 0xb2, 0x45, 0x5e, 0x5d, 0x57, 0xb7, 0x87, 0x75, 0xae, 0xc5, 0x0d, 0x40, 0x61, 0x48, 0x47,
	0xc6, 0x61, 0xde, 0xa2, 0xf7, 0xb2, 0x19, 0xa0, 0x41, 0x8a, 0x2b, 0x58, 0xac, 0x54, 0x0a, 0xfa,
	0x23, 0xa7, 0xab, 0x00, 0xde, 0x65, 0x7c, 0xb2, 0xca, 0xd4, 0xb8, 0x4d, 0x48, 0x50, 0x3f, 0x48,
	0xaa, 0xd9, 0x19, 0x4c, 0x25, 0xd1, 0xeb, 0x86, 0xef, 0xe7, 0x66, 0x2f, 0x12, 0xe9, 0x55, 0x63,
	0xf8, 0x41, 0x4f, 0xa6, 0x3a, 0xad, 0x61, 0xdd, 0x06, 0xdd, 0x9b, 0xe5, 0x93, 0x7e, 0x8d, 0x22,
	0x93, 0x23, 0xd7, 0x6b, 0xbb, 0x33, 0x81, 0x4f, 0x7b, 0xa7, 0xc8, 0x3c, 0x31, 0x12, 0xf2, 0x59,
	0x99, 0x18, 0x09, 0xef, 0xba, 0x0a, 0xe6, 0x2f, 0x0e, 0x31, 0xa0, 0x63, 0x0f, 0xb0, 0xf8, 0x90,
	0x31, 0xbf, 0x95, 0x5d, 0x2c, 0xc7, 0x97, 0x1b, 0xdf, 0xe8, 0xf2, 0xfc, 0x37, 0x8b, 0x74, 0x14,
	0x7b, 0xec, 0x19, 0x4e, 0x86, 0x84, 0xc7, 0x46, 0x2a, 0xf3, 0xbf, 0x98, 0xaf, 0x59, 0xfe, 0xa9,
	0xfb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x61, 0x77, 0x50, 0xbe, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/points_mall.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/points_mall.Greeter/SayHelloAgain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedGreeterServer) SayHelloAgain(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloAgain not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/points_mall.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHelloAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/points_mall.Greeter/SayHelloAgain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHelloAgain(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "points_mall.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayHelloAgain",
			Handler:    _Greeter_SayHelloAgain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "points_mall.proto",
}
