// Code generated by protoc-gen-go. DO NOT EDIT.
// source: points_mall.proto

package points_mall

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayCoinReq struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Sign                 string   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	OrderNo              string   `protobuf:"bytes,4,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Account              string   `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayCoinReq) Reset()         { *m = PayCoinReq{} }
func (m *PayCoinReq) String() string { return proto.CompactTextString(m) }
func (*PayCoinReq) ProtoMessage()    {}
func (*PayCoinReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c75ba8dc07a9bf, []int{0}
}

func (m *PayCoinReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayCoinReq.Unmarshal(m, b)
}
func (m *PayCoinReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayCoinReq.Marshal(b, m, deterministic)
}
func (m *PayCoinReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayCoinReq.Merge(m, src)
}
func (m *PayCoinReq) XXX_Size() int {
	return xxx_messageInfo_PayCoinReq.Size(m)
}
func (m *PayCoinReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayCoinReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayCoinReq proto.InternalMessageInfo

func (m *PayCoinReq) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *PayCoinReq) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *PayCoinReq) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *PayCoinReq) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *PayCoinReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PayCoinReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type PayCoinRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayCoinRsp) Reset()         { *m = PayCoinRsp{} }
func (m *PayCoinRsp) String() string { return proto.CompactTextString(m) }
func (*PayCoinRsp) ProtoMessage()    {}
func (*PayCoinRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7c75ba8dc07a9bf, []int{1}
}

func (m *PayCoinRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayCoinRsp.Unmarshal(m, b)
}
func (m *PayCoinRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayCoinRsp.Marshal(b, m, deterministic)
}
func (m *PayCoinRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayCoinRsp.Merge(m, src)
}
func (m *PayCoinRsp) XXX_Size() int {
	return xxx_messageInfo_PayCoinRsp.Size(m)
}
func (m *PayCoinRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayCoinRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PayCoinRsp proto.InternalMessageInfo

func (m *PayCoinRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*PayCoinReq)(nil), "points_mall.PayCoinReq")
	proto.RegisterType((*PayCoinRsp)(nil), "points_mall.PayCoinRsp")
}

func init() { proto.RegisterFile("points_mall.proto", fileDescriptor_f7c75ba8dc07a9bf) }

var fileDescriptor_f7c75ba8dc07a9bf = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xc8, 0xcf, 0xcc,
	0x2b, 0x29, 0x8e, 0xcf, 0x4d, 0xcc, 0xc9, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x52, 0x9a, 0xc4, 0xc8, 0xc5, 0x15, 0x90, 0x58, 0xe9, 0x9c, 0x9f, 0x99, 0x17, 0x94, 0x5a,
	0x28, 0x24, 0xc4, 0xc5, 0x52, 0x92, 0x99, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04,
	0x66, 0x0b, 0x89, 0x70, 0xb1, 0x26, 0x16, 0x14, 0x78, 0xa6, 0x48, 0x30, 0x81, 0x05, 0x21, 0x1c,
	0x90, 0xca, 0xe2, 0xcc, 0xf4, 0x3c, 0x09, 0x66, 0x88, 0x4a, 0x10, 0x5b, 0x48, 0x82, 0x8b, 0x3d,
	0xbf, 0x28, 0x25, 0xb5, 0xc8, 0x2f, 0x5f, 0x82, 0x05, 0x2c, 0x0c, 0xe3, 0x82, 0x64, 0x12, 0x93,
	0x93, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x58, 0x21, 0x32, 0x50, 0x2e, 0xd8, 0xc6, 0xca, 0x82, 0x54,
	0x09, 0x36, 0xa8, 0x8d, 0x95, 0x05, 0xa9, 0x4a, 0x2a, 0x08, 0x37, 0x15, 0x17, 0x08, 0x89, 0x71,
	0xb1, 0x15, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x80, 0x5d, 0xc5, 0x1a, 0x04, 0xe5, 0x19, 0x79, 0x71,
	0x71, 0x06, 0x80, 0x7c, 0xe2, 0x9b, 0x98, 0x93, 0x23, 0x64, 0xcb, 0xc5, 0x0e, 0xd5, 0x22, 0x24,
	0xae, 0x87, 0xec, 0x67, 0x84, 0xe7, 0xa4, 0xb0, 0x4b, 0x14, 0x17, 0x28, 0x31, 0x38, 0xc9, 0x47,
	0xc9, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xe7, 0x66, 0x59, 0x9a,
	0x1a, 0x99, 0xeb, 0x23, 0xa9, 0x4e, 0x62, 0x03, 0x87, 0x9d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x78, 0x79, 0x72, 0x69, 0x50, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PointMallClient is the client API for PointMall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PointMallClient interface {
	PayCoin(ctx context.Context, in *PayCoinReq, opts ...grpc.CallOption) (*PayCoinRsp, error)
}

type pointMallClient struct {
	cc *grpc.ClientConn
}

func NewPointMallClient(cc *grpc.ClientConn) PointMallClient {
	return &pointMallClient{cc}
}

func (c *pointMallClient) PayCoin(ctx context.Context, in *PayCoinReq, opts ...grpc.CallOption) (*PayCoinRsp, error) {
	out := new(PayCoinRsp)
	err := c.cc.Invoke(ctx, "/points_mall.PointMall/PayCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointMallServer is the server API for PointMall service.
type PointMallServer interface {
	PayCoin(context.Context, *PayCoinReq) (*PayCoinRsp, error)
}

// UnimplementedPointMallServer can be embedded to have forward compatible implementations.
type UnimplementedPointMallServer struct {
}

func (*UnimplementedPointMallServer) PayCoin(ctx context.Context, req *PayCoinReq) (*PayCoinRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayCoin not implemented")
}

func RegisterPointMallServer(s *grpc.Server, srv PointMallServer) {
	s.RegisterService(&_PointMall_serviceDesc, srv)
}

func _PointMall_PayCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayCoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointMallServer).PayCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/points_mall.PointMall/PayCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointMallServer).PayCoin(ctx, req.(*PayCoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PointMall_serviceDesc = grpc.ServiceDesc{
	ServiceName: "points_mall.PointMall",
	HandlerType: (*PointMallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayCoin",
			Handler:    _PointMall_PayCoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "points_mall.proto",
}
